### ISSUE TITLE
Disconnect workflow input output

### ISSUE THREAD

**Issue by sunshineyyy** [aquarium-bio/issues#11]
Currently it's easy to connect input and output of operations but I can not find an easy way to disconnect them using the GUI yet.

**Comment by klavins** [comment]
In fact, this issue is bigger. When you delete an operation or i/o that is connected to something else, the link does not get deleted, it just becomes invisible. Then, when you try to run the workflow, an opration may not start if it is waiting for another input operation that doesn't exist yet to which it is connected.

**Comment by klavins** [comment]
This has been fixed. Half connected connections show as such. And when you select a connection, a button shows up in the workflow info box that you can use to delete the connection.
