### ISSUE TITLE
Issues with names of samples

### ISSUE THREAD

**Issue by lauraadam** [aquarium-bio/issues#29]
I didn't realize, my task (http://54.68.9.194:81/tasks/15450) is failed but the fragment (http://54.68.9.194:81/samples/11616) has successfully been constructed and has been virtually 'moved' to that http://54.68.9.194:81/samples/9681 (I guess the have the same name, just different case).

Along these lines.
I also notice that if I change a primer name that had been used for a fragment construction i.e. it has been ordered -say primerA becomes primerA_error, it is no longer attached to the fragment. If I reused the name for a corrected primerA,  and re-start the fragment construction, it submit a primer order (because there is  no stock) for the old primer id, because the name of the task....  I think the convention should change.

**Comment by sunshineyyy** [comment]
The first problem was due to that Laura's fragment has the almost the same name with Lauren's except for lower or upper cases. When producing the fragment stock in the gel_purify protocol, I used the syntax of 
produce new_sample "PS_ubiYdKyeGFP_TP", of: "Fragment", as: "Fragment Stock"
this actually produced fragment stock under Lauren's fragment ps_ubiYdKyeGFP_tp. 
I think the problem originates from find_by_name function in Aquarium/Rails that being used in find function. The find_by_name function seems to be case-insensitive. I change to use
sample.make_item "Fragment Stock"
to make new fragment stock in the protocol and it will not make 'wrong' fragment stock anymore. But we might want to consider changing the find function in Aquarium to be case-sensitive.

**Comment by sunshineyyy** [comment]
For the second problem you described, I plan to change the primer order so that if you already have a primer stock in inventory, it will not order for you and move a status called duplicated or something so that the researcher can review it and make sure they really want an additional primer orders.

**Comment by sunshineyyy** [comment]
I have updated the code in the primer order workflow so that if a primer already has primer stock in the inventory, it will stay in waiting and no chance to be ordered from IDT.
